DETERMINISTIC_PARAMETERS = [
    {
        "key": "alkaline_lifetime_hours",
        "label": "AE electrolyser lifetime hours",
        "default": 75000,
        "unit": "hrs",
        "reference": "International Energy Agency, (2019)",
    },
    {
        "key": "alkaline_lifetime_growth_per_year",
        "label": "AE electrolyser lifetime hours growth per year",
        "default": 1667,
        "unit": "hrs",
        "reference": "International Energy Agency, (2019)",
    },
    {
        "key": "pem_lifetime_hours",
        "label": "PEM electrolyser lifetime hours",
        "default": 60000,
        "unit": "hrs",
        "reference": "International Energy Agency, (2019)",
    },
    {
        "key": "pem_lifetime_growth_per_year",
        "label": "PEM electrolyser lifetime hours growth per year",
        "default": 2250,
        "unit": "hrs",
        "reference": "International Energy Agency, (2019)",
    },
    {
        "key": "soec_lifetime_hours",
        "label": "SOE lifetime hours",
        "default": 20000,
        "unit": "hrs",
        "reference": "International Energy Agency, (2019)",
    },
    {
        "key": "soec_lifetime_growth_per_year",
        "label": "SOE lifetime hours growth per year",
        "default": 2167,
        "unit": "hrs",
        "reference": "International Energy Agency, (2019)",
    },
    {
        "key": "alkaline_efficiency_growth_per_year",
        "label": "AE electrolyser efficiency growth per year",
        "default": 0.00267,
        "unit": "–",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "pem_efficiency_growth_per_year",
        "label": "PEM electrolyser efficiency growth per year",
        "default": 0.004,
        "unit": "–",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "soec_efficiency_growth_per_year",
        "label": "SOE efficiency growth per year",
        "default": 0.00267,
        "unit": "–",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "wind_capex_growth_pre_2030",
        "label": "Wind power CapEx growth per year",
        "default": -0.0225,
        "unit": "–",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "wind_turbine_efficiency",
        "label": "Wind turbine efficiency",
        "default": 0.4,
        "unit": "–",
        "reference": "International Renewable Energy Agency, (2016)",
    },
    {
        "key": "wind_turbine_blade_size",
        "label": "Wind turbine blade size",
        "default": 50,
        "unit": "m",
        "reference": "International Renewable Energy Agency, (2016)",
    },
    {
        "key": "wind_turbine_lifetime",
        "label": "Wind turbine lifetime",
        "default": 30,
        "unit": "y",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "solar_capex_growth_per_year",
        "label": "Solar power CapEx growth per year",
        "default": -0.0014,
        "unit": "–",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "solar_efficiency_base",
        "label": "Solar efficiency",
        "default": 0.64,
        "unit": "–",
        "reference": "Jäger-Waldau, (2019)",
    },
    {
        "key": "solar_efficiency_growth_per_year",
        "label": "Solar efficiency growth per year",
        "default": 0.00333,
        "unit": "–",
        "reference": "Jäger-Waldau, (2019)",
    },
    {
        "key": "solar_pv_lifetime",
        "label": "Solar PV lifetime",
        "default": 30,
        "unit": "y",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "compressor_electricity_consumption",
        "label": "Compressor electricity consumption",
        "default": 4,
        "unit": "MWh/ton H₂",
        "reference": "Parks et al. (2014)",
    },
    {
        "key": "full_load_hours",
        "label": "Full load hours",
        "default": 2000,
        "unit": "hrs/y",
        "reference": "Christensen, (2020)",
    },
    {
        "key": "discount_rate",
        "label": "Discount rate",
        "default": 0.08,
        "unit": "–",
        "reference": "Brennan, (2020)",
    },
    {
        "key": "further_capex_costs",
        "label": "Further CapEx costs (piping, electrical)",
        "default": 43,
        "unit": "€/kW",
        "reference": "Glenk and Reichelstein, (2019)",
    },
]


MC_PARAMETERS = [
    {
        "label": "Wind CapEx",
        "unit": "€/kW",
        "distribution": "Triangular",
        "source": "International Renewable Energy Agency, (2012)",
        "lower_key": "wind_capex_lower",
        "lower": 1200,
        "middle_key": "wind_capex_middle",
        "middle": 1260,
        "upper_key": "wind_capex_upper",
        "upper": 1500,
    },
    {
        "label": "Wind OpEx",
        "unit": "€/MWh",
        "distribution": "Triangular",
        "source": "International Renewable Energy Agency, (2016)",
        "lower_key": "wind_opex_lower",
        "lower": 6,
        "middle_key": "wind_opex_middle",
        "middle": 8,
        "upper_key": "wind_opex_upper",
        "upper": 10,
    },
    {
        "label": "Solar CapEx",
        "unit": "€/kWp",
        "distribution": "Triangular",
        "source": "Mayer et al. (2015); Jäger-Waldau. (2019)",
        "lower_key": "solar_capex_lower",
        "lower": 500,
        "middle_key": "solar_capex_middle",
        "middle": 700,
        "upper_key": "solar_capex_upper",
        "upper": 1100,
    },
    {
        "label": "Solar OpEx factor",
        "unit": "–",
        "distribution": "Triangular",
        "source": "Mayer et al. (2015); Jäger-Waldau. (2019)",
        "lower_key": "solar_opex_lower",
        "lower": 0.01,
        "middle_key": "solar_opex_middle",
        "middle": 0.015,
        "upper_key": "solar_opex_upper",
        "upper": 0.02,
    },
    {
        "label": "AE electrolyser CapEx",
        "unit": "€/kW",
        "distribution": "Triangular",
        "source": "Glenk and Reichelstein, (2019); Christensen. (2020)",
        "lower_key": "ae_electrolyser_capex_lower",
        "lower": 477,
        "middle_key": "ae_electrolyser_capex_middle",
        "middle": 830,
        "upper_key": "ae_electrolyser_capex_upper",
        "upper": 1060,
    },
    {
        "label": "PEM electrolyser CapEx",
        "unit": "€/kW",
        "distribution": "Triangular",
        "source": "Glenk and Reichelstein. (2019); Christensen. (2020)",
        "lower_key": "pem_electrolyser_capex_lower",
        "lower": 322,
        "middle_key": "pem_electrolyser_capex_middle",
        "middle": 994,
        "upper_key": "pem_electrolyser_capex_upper",
        "upper": 1731,
    },
    {
        "label": "SOE CapEx",
        "unit": "€/kW",
        "distribution": "Triangular",
        "source": "Glenk and Reichelstein. (2019); Christensen. (2020)",
        "lower_key": "soe_electrolyser_capex_lower",
        "lower": 566,
        "middle_key": "soe_electrolyser_capex_middle",
        "middle": 1131,
        "upper_key": "soe_electrolyser_capex_upper",
        "upper": 1912,
    },
    {
        "label": "Electrolyser CapEx growth",
        "unit": "–",
        "distribution": "Triangular",
        "source": "Christensen, (2020)",
        "lower_key": "electrolyser_capex_growth_lower",
        "lower": 0.975,
        "middle_key": "electrolyser_capex_growth_middle",
        "middle": 0.98,
        "upper_key": "electrolyser_capex_growth_upper",
        "upper": 0.995,
    },
    {
        "label": "Electrolyser OpEx",
        "unit": "–",
        "distribution": "Triangular",
        "source": "Brynolf et al. (2018)",
        "lower_key": "electrolyser_opex_lower",
        "lower": 0.01,
        "middle_key": "electrolyser_opex_middle",
        "middle": 0.015,
        "upper_key": "electrolyser_opex_upper",
        "upper": 0.02,
    },
    {
        "label": "AE electrolyser efficiency",
        "unit": "–",
        "distribution": "Uniform",
        "source": "International Energy Agency, (2019)",
        "lower_key": "ae_efficiency_lower",
        "lower": 0.67,
        "upper_key": "ae_efficiency_upper",
        "upper": 0.7,
    },
    {
        "label": "PEM electrolyser efficiency",
        "unit": "–",
        "distribution": "Uniform",
        "source": "International Energy Agency, (2019)",
        "lower_key": "pem_efficiency_lower",
        "lower": 0.58,
        "upper_key": "pem_efficiency_upper",
        "upper": 0.6,
    },
    {
        "label": "SOE efficiency",
        "unit": "–",
        "distribution": "Uniform",
        "source": "International Energy Agency, (2019)",
        "lower_key": "soe_efficiency_lower",
        "lower": 0.77,
        "upper_key": "soe_efficiency_upper",
        "upper": 0.81,
    },
    {
        "label": "AE external electrolyser CapEx",
        "unit": "€/kg H₂",
        "distribution": "Triangular",
        "source": "Parks et al. (2014)",
        "lower_key": "ae_external_capex_lower",
        "lower": 2.30,
        "middle_key": "ae_external_capex_middle",
        "middle": 2.47,
        "upper_key": "ae_external_capex_upper",
        "upper": 2.65,
    },
    {
        "label": "PEM external electrolyser CapEx",
        "unit": "€/kg H₂",
        "distribution": "Triangular",
        "source": "Parks et al. (2014)",
        "lower_key": "pem_external_capex_lower",
        "lower": 0.8,
        "middle_key": "pem_external_capex_middle",
        "middle": 0.91,
        "upper_key": "pem_external_capex_upper",
        "upper": 1,
    },
    {
        "label": "SOE external CapEx",
        "unit": "€/kg H₂",
        "distribution": "Triangular",
        "source": "Parks et al. (2014)",
        "lower_key": "soe_external_capex_lower",
        "lower": 2.30,
        "middle_key": "soe_external_capex_middle",
        "middle": 2.47,
        "upper_key": "soe_external_capex_upper",
        "upper": 2.65,
    },
    {
        "label": "Electrolyser water",
        "unit": "€/kg H₂",
        "distribution": "Triangular",
        "source": "Christensen, (2020)",
        "lower_key": "electrolyser_water_lower",
        "lower": 0.05,
        "middle_key": "electrolyser_water_middle",
        "middle": 0.07,
        "upper_key": "electrolyser_water_upper",
        "upper": 0.09,
    },
]
